version: 2.1
orbs:
  node: circleci/node@5.1.0
  rust: circleci/rust@1.6.0
jobs:
  run_forge_tests:
    docker:
      - image: ghcr.io/foundry-rs/foundry:latest
    steps:
      - checkout
      - run:
          name: run foundry tests
          command: forge test --via-ir
          working_directory: src/contracts

  run_unit_and_e2e_tests:
    working_directory: ~/zk-email-verify/twitter-verifier
    docker:
      - image: cimg/node:16.19-browsers
    steps:
      - checkout:
          path: ~/zk-email-verify
      - run: node --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run unit tests
          environment:
            JEST_JUNIT_OUTPUT: reports/unit-test-results.xml
      - run:
          command: CI=false yarn run build
          name: Build app
      - run:
          command: yarn run start-e2e-test-server
          name: Start test server
          background: true
      - run:
          command: yarn test:e2e-ui
          name: Run e2e tests for UI
          environment:
            JEST_JUNIT_OUTPUT: reports/e2e-ui-test-results.xml

      # - run:
      #     command: yarn test:e2e-zkp
      #     name: Run e2e tests for zkp
      #     environment:
      #       JEST_JUNIT_OUTPUT: reports/e2e-zkp-test-results.xml
      - store_test_results:
          path: reports/
workflows:
  build_test: 
    jobs:
      - run_unit_and_e2e_tests
      - run_forge_tests