[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-circom = { git = "https://github.com/gakonst/ark-circom.git", rev = "170b10fc9ed182b5f72ecf379033dda023d0bf07" }
ark-crypto-primitives = { version = "=0.4.0" }
ark-ec = { version = "=0.4.1", default-features = false, features = ["parallel"] }
ark-ff = { version = "=0.4.1", default-features = false, features = ["parallel", "asm"] }
ark-bn254 = { version = "=0.4.0" }
ark-groth16 = { version = "=0.4.0", default-features = false, features = ["parallel"] }
ark-serialize = { version = "=0.4.1", default-features = false }

serde_json = "=1.0.94"
serde = "*"
clap = { version = "4.0", features = ["derive"] }
